# Build Stage 
FROM node:12 as build
WORKDIR /build
COPY . .
COPY package.json package-lock.json* .env* ./
RUN npm install
RUN npm run build

# ----------------------------------------------------------------
# SERVE STAGE
# ----------------------------------------------------------------
FROM node:12-alpine as serve
WORKDIR /opt/app
COPY package.json package-lock.json* .env* ./
COPY --from=build /build/dist ./dist
RUN npm install --only=prod
CMD ["node", "dist/app.js"]